### ISSUE TITLE
Add option to specify the output number of pages when importing a folder.

### ISSUE THREAD

**Issue by ZeroCool940711** [Aeonss/StitchTool#2]
It would be nice to have an option to specify how many pages we want to have after importing a whole folder and stitching all the images together, right now the result is a single page with all the images together as one, would be nice to have it split into a set of pages, for example instead of a single page we could have 10 pages, this could be useful when stitching together a webtoon with lots of pages and then splitting it into just a few pages.

**Comment by Aeonss** [comment]
Hello, I will fix bugs and update the tool once finals weeks is over!

**Comment by ZeroCool940711** [comment]
@Aeonss Sure, no problem, take your time, I'm glad you are still updating this tool and keeping an eye on the repository, I really like this tool, in my case more than using it for splitting webtoons I use it to stitch them together as I always find some chapters that have just too many pieces and it makes it hard to read that way and so I have to stitch them in a way that is easier to read. Keep the good work and good luck on your finals.

**Comment by Aeonss** [comment]
Added option to stitch and split at the same time with the 6 possible permutations. (Read commit message for more)

Let me know if you find any bugs and I will try to fix them asap!

**Comment by Aeonss** [comment]
> It would be nice to have an option to specify how many pages we want to have after importing a whole folder and stitching all the images together, right now the result is a single page with all the images together as one, would be nice to have it split into a set of pages, for example instead of a single page we could have 10 pages, this could be useful when stitching together a webtoon with lots of pages and then splitting it into just a few pages.

Added option to stitch and split at the same time with the 6 possible permutations. (Read commit message for more)

Let me know if you find any bugs and I will try to fix them asap!
