### ISSUE TITLE
Could not find or load main class.

### ISSUE THREAD

**Issue by ZeroCool940711** [Aeonss/StitchTool#3]
Hi there, seems like I can't run Stitch anymore for some reason, it was previously working, previous version was running normally but now I can't run the new version, I get the following error:
```
Error: Could not find or load main class StitchTool.v3.1.1.jar
Caused by: java.lang.ClassNotFoundException: StitchTool.v3.1.1.jar
```

Is it a problem with the new jar file or is it a problem with my computer?, Java is installed and as I said a previous version was working.

**Comment by Aeonss** [comment]
Are you running by cmd or by double clicking?

**Comment by ZeroCool940711** [comment]
I tried running it using double click but nothing happens when I do it, so, I tried using a console to run it and then I got that error, funny thing is I tried running the old version that I was using but now I cant run it either, nothing has changed on my computer since last time I used StitchTool .-.

**Comment by Aeonss** [comment]
I just released v3.2.0, see if that is working. I can't replicate your issue on my PC, but I'll ask a friend if he gets the same issue.

**Comment by ZeroCool940711** [comment]
The new version doesn't work either, I do not think it's a problem with the jar file but rather a problem with my computer, god knows what happened, maybe Windows Update broke something and I didn't notice until I tried running StitchTool, would be nice if you could release the new versions as an exe file instead of a jar so we can run it without depending on java and so we can avoid issues like this one I'm having, pretty sure I'm not the first and won't be the last to have this issue xD

**Comment by ZeroCool940711** [comment]
Seems like it is not my computer, I tried running another jar file from another software I found to test if java was running correctly and seems like everything is okay, it probably is because of some dependency StitchTool is using which cant be found when trying to run the jar file.

**Comment by Aeonss** [comment]
> Seems like it is not my computer, I tried running another jar file from another software I found to test if java was running correctly and seems like everything is okay, it probably is because of some dependency StitchTool is using which cant be found when trying to run the jar file.

I've put out a hotfix, let me know if you can run it from cmd or double clicking on it. I'm not sure what happened for it to be like this :((

**Comment by ZeroCool940711** [comment]
Here is some extra info, this is what I get when running the jar using `java -jar StitchTool.v3.2.0.jar` from the console:
```
D:\StitchTool>java -jar StitchTool.v3.2.0.jar

Dec 18, 2021 2:38:32 PM com.sun.javafx.application.PlatformImpl startup
WARNING: Unsupported JavaFX configuration: classes were loaded from 'unnamed module @3454e17c'
Graphics Device initialization failed for :  d3d, sw
Error initializing QuantumRenderer: no suitable pipeline found
java.lang.RuntimeException: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
        at com.sun.javafx.tk.quantum.QuantumRenderer.getInstance(QuantumRenderer.java:283)
        at com.sun.javafx.tk.quantum.QuantumToolkit.init(QuantumToolkit.java:254)
        at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:264)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:291)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:163)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:659)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:679)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
        at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.RuntimeException: Error initializing QuantumRenderer: no suitable pipeline found
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.init(QuantumRenderer.java:95)
        at com.sun.javafx.tk.quantum.QuantumRenderer$PipelineRunnable.run(QuantumRenderer.java:125)
        ... 1 more
Exception in thread "main" java.lang.RuntimeException: No toolkit found
        at com.sun.javafx.tk.Toolkit.getToolkit(Toolkit.java:276)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:291)
        at com.sun.javafx.application.PlatformImpl.startup(PlatformImpl.java:163)
        at com.sun.javafx.application.LauncherImpl.startToolkit(LauncherImpl.java:659)
        at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:679)
        at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$2(LauncherImpl.java:196)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by ZeroCool940711** [comment]
I manage to fix it partially and found something interesting, seems like it is because of JavaFX, on older versions of the java jdk like v14.0.2 that library seems to be included on the default libs but on newer versions it is not included, my reasoning for this is that I tried with java jdk v15, v16 and v17 and none even opened the UI for StitchTool and I was getting the error from before but with java v14 the UI opened, you also need the JRE, the latest version works fine, as of now it is JRE 8 update 311, I still havent managed to run the jar using double click, it runs if I use the console and pass the -jar parameter to java but when double clicking the jar it does nothing, I tried older versions and still got the same behavior.

**Comment by ZeroCool940711** [comment]
I managed to fix the double click issue, seems like it was because I previously used `Rick Click > Open With` and used `javaw.exe` to open a jar file when testing for possible fixes and that caused the registry key for the jar extension to get broken, I found [this link](https://stackoverflow.com/a/30571306) which solved the problem and now the jar files open normally with double click, I'm leaving all this info here to let you know that I fixed the issue and also in case someone else have the same issue.

**Comment by Aeonss** [comment]
> I managed to fix the double click issue, seems like it was because I previously used `Rick Click > Open With` and used `javaw.exe` to open a jar file when testing for possible fixes and that caused the registry key for the jar extension to get broken, I found [this link](https://stackoverflow.com/a/30571306) which solved the problem and now the jar files open normally with double click, I'm leaving all this info here to let you know that I fixed the issue and also in case someone else have the same issue.

Glad you could fix it. I'm dropping a beta version of StitchTool which is now bundled with JavaFX, can you let me know if it works?

**Comment by ZeroCool940711** [comment]
- First, nice icon for the `.exe` file 10/10.
- Second, I found a couple of problems with all the versions after 3.0, meaning all the versions after you introduced the Waifu2x denoise and upscaling feature, the first one is a small bug but this message is shown twice, when you specify the number of images to split the image into you get asked again the same thing
![image](https://user-images.githubusercontent.com/5977640/146658057-5eaa4833-293d-4adf-b7be-6957f7285df7.png)
- Third, seems like if you do not download waifu2x and add it using the `Import Waifu2x` option the program doesn't work even if you do not use the denoise option at all, if you try to split an image after each split you get an error saying that waifu2x can't be found. 
![image](https://user-images.githubusercontent.com/5977640/146658113-c90e2ff9-634e-4bb6-b3c3-802bdd2c193a.png)
When that happens after all the splits are done the folder and images are deleted, and yes I checked the output folder and none of the images are there, they are just deleted, when the waifu2x location is added correctly the images are moved from the StitchTool folder created inside the output location to the root of the output location correctly but not when you do not use waifu2x, using waifu2x should be optional and the program should run even without it.

**Comment by ZeroCool940711** [comment]
The new version does work correctly now, it was indeed a problem with JavaFX, just to make sure I used the java jdk v17 and now it runs the jar file without any problem, I also tried again an older version of StitchTool and that older version didnt work with java jdk v17, so, the problem was JavaFX not been included in the new version of the jdk, now that you have it bundled into StitchTool it works on any version.

**Comment by Aeonss** [comment]
> > Glad you could fix it. I'm dropping a beta version of StitchTool which is now bundled with JavaFX, can you let me know if it works?
> > https://github.com/Aeonss/StitchTool/releases/tag/3.3.0
> 
> The new version does work correctly now, it was indeed a problem with JavaFX, just to make sure I used the java jdk v17 and now it runs the jar file without any problem, I also tried again an older version of StitchTool and that older version didnt work with java jdk v17, so, the problem was JavaFX not been included in the new version of the jdk, now that you have it bundled into StitchTool it works on any version.

Great! Thanks so much for your feedback, it helps me out immensely. I fixed the issue with the waifu2x being called even though it wasn't imported. However I couldn't replicate the issue where splitting would ask you to specify the amount of images you want to split into multiple times.

**Comment by ZeroCool940711** [comment]
> Great! Thanks so much for your feedback, it helps me out immensely. I fixed the issue with the waifu2x being called even though it wasn't imported. However I couldn't replicate the issue where splitting would ask you to specify the amount of images you want to split into multiple times.

Glad to help, regarding the double message I'm not sure what it could be, maybe it asks during the Stitch and then for the Split part too? 
BTW, here are the options I'm using, as you can see on this screenshot Im using the `Stitch Vertically, Smart Split` option, as they are two actions now and previously it was only one thing maybe that's why I'm getting two messages for the same thing.
![image](https://user-images.githubusercontent.com/5977640/146658528-266475bc-a52c-432f-829c-722c0a39db8c.png)

Also, I'm getting this empty message after the first split, also found a bug, seems like  the resulting images after the split are been saved as a single image, in my case I configured the `File Name` to be `0000`, StitchTool is spliting things correctly inside the StitchTool folder but then it moves the images to the Output Location and each split is saved using the same File Name which is `0000.png`, that causes the original file to be replaced and only the latest split is saved, on the previous version (StitchTool_v3.3.0) this was not happening.
![image](https://user-images.githubusercontent.com/5977640/146658476-be8c2905-a5d8-4137-9e89-cdef7619e50b.png)

**Comment by Aeonss** [comment]
> > Great! Thanks so much for your feedback, it helps me out immensely. I fixed the issue with the waifu2x being called even though it wasn't imported. However I couldn't replicate the issue where splitting would ask you to specify the amount of images you want to split into multiple times.
> 
> Glad to help, regarding the double message I'm not sure what it could be, maybe it asks during the Stitch and then for the Split part too? BTW, here are the options I'm using, as you can see on this screenshot Im using the `Stitch Vertically, Smart Split` option, as they are two actions now and previously it was only one thing maybe that's why I'm getting two messages for the same thing. ![image](https://user-images.githubusercontent.com/5977640/146658528-266475bc-a52c-432f-829c-722c0a39db8c.png)
> 
> Also, I'm getting this empty message after the first split, also found a bug, seems like the resulting images after the split are been saved as a single image when USING waifu2x denoise but not when you disable it, in my case I configured the `File Name` to be `0000`, StitchTool is splitting things correctly inside the StitchTool folder but then it moves the images to the Output Location after each split and each one is saved using the same File Name which is `0000.png`, that causes the original file to be replaced and only the latest split is saved, on the previous version (StitchTool_v3.3) this was not happening, it also does not happen if you disable the denoise option which then doesnt use Waifu2x at all, also when waifu2x is disabled after the images are processed they are not moved to the Output Location and are left inside the StitchTool folder. ![image](https://user-images.githubusercontent.com/5977640/146658476-be8c2905-a5d8-4137-9e89-cdef7619e50b.png)
> 
> Another small note, the `Waifu2X Caffe Location` should be remembered between restarts of StitchTool, that way its easier and faster to use the program without having to configure a lot of stuff every time.

Fixed mentioned issues
