### ISSUE TITLE
Image being deleted after stitched/splited?

### ISSUE THREAD

**Issue by ToxicRT** [Aeonss/StitchTool#5]
Hello, i was giving a try to this app but i got a problem after stitching or spliting because the image is being deleted of the output folder, i dont know if this only happens to me. :/

**Comment by Aeonss** [comment]
Can you list the steps that you did (and the options you chose) which caused the image to be deleted?

**Comment by ToxicRT** [comment]
1: i selected 2 images in a folder
2: denoise disabled
3: stitch option and vertical
4: run

after this i get 2 warn box
![image](https://user-images.githubusercontent.com/43280922/147498167-31edee8e-0000-4870-91ea-642e52a702ee.png)

after the image of above i get another box about stitching complete and the image its automatically deleted of the output folder
![image](https://user-images.githubusercontent.com/43280922/147498132-cf6c3111-5115-43e9-9a56-8f81e990a5d7.png)

**Comment by Aeonss** [comment]
Fixed in v3.3.8. Let me know if you find something like this again
