### ISSUE TITLE
Smartplit black background

### ISSUE THREAD

**Issue by Loyute** [Aeonss/StitchTool#6]
smartsplit cannot split into the black background

**Comment by Aeonss** [comment]
> 

Can you post the image you used for smartsplit?

**Comment by Loyute** [comment]
Normally each image is about 15000 pixels height on average, and this one is 38000 pixels height
Here is the image that has not been split
https://ibb.co/q9kTW27

**Comment by Aeonss** [comment]
> Normally each image is about 15000 pixels height on average, and this one is 38000 pixels height Here is the image that has not been split https://ibb.co/q9kTW27
> 
> and i can't post the full image bedcuase is too big

Fixed issue in latest release. Download the jar from releases or from https://www.jdeploy.com/~stitchtool
