### ISSUE TITLE
 Watermarks [Error and recommendation]

### ISSUE THREAD

**Issue by DreamS18** [Aeonss/StitchTool#7]
Hi, in the new versions of Stitch, the option to create watermarks doesn't work, it asks you for the two images as usual, and after that it doesn't show you the box asking how many watermarks you want.
And an additional recommendation, could be to have the option to change the size of the watermark, because the rescaling makes the watermark very small, and this makes it easy to erase it by other groups.

Nice tool, thanks.

**Comment by Aeonss** [comment]
Thank you for reporting the bug. I have fixed it and added the option for you to select the width % of the watermark.

Example:

You want to put image B (the watermark) on image A (the manga/manhwa).

You can input of image B by giving it a percent of the width of image A.

Entering 100 will make it so image B will be the full width of image A.

Entering 25 will make it so image B is 25% the width of image A.
